/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Peticiones;

import Views.AdministrarUsuarios;
import java.awt.BorderLayout;

/**
 *
 * @author 1gdaw09
 */
public class AdministradorPanel extends javax.swing.JPanel {

   public void Peticiones(){
//Visualizacion de paneles     
        Peticiones c1 = new Peticiones();
        c1.setSize(991, 578);
        c1.setLocation(0, 0);

        PAdministradorPrincipal.removeAll();
        PAdministradorPrincipal.add(c1, BorderLayout.CENTER);
        PAdministradorPrincipal.revalidate();
        PAdministradorPrincipal.repaint();
    }
   
    public void AjustesJornadas(){
//Visualizacion de paneles     
        AjustesJornadasPanel c1 = new AjustesJornadasPanel();
        c1.setSize(991, 578);
        c1.setLocation(0, 0);

        PAdministradorPrincipal.removeAll();
        PAdministradorPrincipal.add(c1, BorderLayout.CENTER);
        PAdministradorPrincipal.revalidate();
        PAdministradorPrincipal.repaint();
    }
   
    public void AjustesPartidos(){
//Visualizacion de paneles     
        AjustesPartidosPanel c1 = new AjustesPartidosPanel();
        c1.setSize(991, 578);
        c1.setLocation(0, 0);

        PAdministradorPrincipal.removeAll();
        PAdministradorPrincipal.add(c1, BorderLayout.CENTER);
        PAdministradorPrincipal.revalidate();
        PAdministradorPrincipal.repaint();
    }
   
   
   
   
   
   
    public AdministradorPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BPeticiones = new javax.swing.JButton();
        BAjusteJornada = new javax.swing.JButton();
        PAdministradorPrincipal = new javax.swing.JPanel();
        BAjustePartidos = new javax.swing.JButton();

        BPeticiones.setBackground(new java.awt.Color(255, 255, 255));
        BPeticiones.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BPeticiones.setText("Peticiones");
        BPeticiones.setBorder(null);
        BPeticiones.setBorderPainted(false);
        BPeticiones.setFocusable(false);
        BPeticiones.setOpaque(false);
        BPeticiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPeticionesActionPerformed(evt);
            }
        });

        BAjusteJornada.setBackground(new java.awt.Color(255, 255, 255));
        BAjusteJornada.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BAjusteJornada.setText("Ajustes Jornadas");
        BAjusteJornada.setBorder(null);
        BAjusteJornada.setBorderPainted(false);
        BAjusteJornada.setFocusable(false);
        BAjusteJornada.setOpaque(false);
        BAjusteJornada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAjusteJornadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PAdministradorPrincipalLayout = new javax.swing.GroupLayout(PAdministradorPrincipal);
        PAdministradorPrincipal.setLayout(PAdministradorPrincipalLayout);
        PAdministradorPrincipalLayout.setHorizontalGroup(
            PAdministradorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 865, Short.MAX_VALUE)
        );
        PAdministradorPrincipalLayout.setVerticalGroup(
            PAdministradorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
        );

        BAjustePartidos.setBackground(new java.awt.Color(255, 255, 255));
        BAjustePartidos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BAjustePartidos.setText("Ajustes Partidos");
        BAjustePartidos.setBorder(null);
        BAjustePartidos.setBorderPainted(false);
        BAjustePartidos.setFocusable(false);
        BAjustePartidos.setOpaque(false);
        BAjustePartidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAjustePartidosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PAdministradorPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BPeticiones, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BAjusteJornada, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(BAjustePartidos, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BPeticiones)
                    .addComponent(BAjusteJornada)
                    .addComponent(BAjustePartidos))
                .addGap(52, 52, 52)
                .addComponent(PAdministradorPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BPeticionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPeticionesActionPerformed

        //LLamar a la clase
        Peticiones();
    }//GEN-LAST:event_BPeticionesActionPerformed

    private void BAjusteJornadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAjusteJornadaActionPerformed

        //LLamar a la clase
         AjustesJornadas();
    }//GEN-LAST:event_BAjusteJornadaActionPerformed

    private void BAjustePartidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAjustePartidosActionPerformed
   
        //LLamar a la clase
        AjustesPartidos();
    }//GEN-LAST:event_BAjustePartidosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAjusteJornada;
    private javax.swing.JButton BAjustePartidos;
    private javax.swing.JButton BPeticiones;
    private javax.swing.JPanel PAdministradorPrincipal;
    // End of variables declaration//GEN-END:variables
}
