
package Views.Peticiones;

import UML.Duenno;
import UML.Equipo;
import UML.Jugador;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import static javax.swing.JOptionPane.showMessageDialog;
import master_esport.Master_ESport;


public class Peticiones extends javax.swing.JPanel {
    
    public Peticiones() {
        initComponents();
        listaPeticiones();
    }
    
    public void listaPeticiones(){
    
        try {
            
            Master_ESport.verPeticionDuennos();
            Master_ESport.verPeticionEquipos();
            Master_ESport.verPeticionJugadores();
            
            jpl.setModel(Master_ESport.list);

            
        } catch (Exception ex) {
            Logger.getLogger(Peticiones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void aceptarPeticionDuenno(int r){
    
        try {
            
            ArrayList <Duenno> d = Master_ESport.verPeticionDuenno();
            Master_ESport.anadirDuenno(d.get(r));
            Master_ESport.borrarPeticion(d.get(r).getNickname());
            
            Master_ESport.list.remove(r);
            
            showMessageDialog(this, "Peticion aceptada");
            
        }
        catch (Exception e) {
            
            showMessageDialog(this, e.getMessage());
        }
    }
    
    public void denegarPeticionDuenno(int r){
        
        try {
            
            ArrayList <Duenno> d = Master_ESport.verPeticionDuenno();
            Master_ESport.borrarPeticion(d.get(r).getNickname());
            
            Master_ESport.list.remove(r);
            
            showMessageDialog(this, "Peticion denegada");
            
        }
        catch (Exception e) {
            
            showMessageDialog(this, e.getMessage());
        }

    }
    
    public void aceptarPeticionEquipo(int r){
        
        try {
                         
            ArrayList <Equipo> d = Master_ESport.verPeticionEquipo();
            
            Master_ESport.anadirEquipo(d.get(r));
            Master_ESport.borrarPeticionN(d.get(r).getNombre());
            
            Master_ESport.list.remove(r);
            
            showMessageDialog(this, "Peticion aceptada");
            
        }
        catch (Exception e) {
            
            showMessageDialog(this, e.getMessage());
        }
    }
    
    public void denegarPeticionEquipo(int r){
    
        try {
            
            ArrayList <Equipo> d = Master_ESport.verPeticionEquipo();
            Master_ESport.borrarPeticionN(d.get(r).getNombre());
            
            Master_ESport.list.remove(r);
            
            showMessageDialog(this, "Peticion denegada");
            
        }
        catch (Exception e) {
            
            showMessageDialog(this, e.getMessage());
        }

    }
    
    public void aceptarPeticionJugador(int r){
        
        try {
                         
            ArrayList <Jugador> d = Master_ESport.verPeticionJugador();
            
            Master_ESport.anadirJugador(d.get(r));
            Master_ESport.borrarPeticion(d.get(r).getNombre());
            
            Master_ESport.list.remove(r);
            
            showMessageDialog(this, "Peticion aceptada");
            
        }
        catch (Exception e) {
            
            showMessageDialog(this, e.getMessage());
        }
    }
    
    public void denegarPeticionJugador(int r){
    
        try {
            
            ArrayList <Jugador> d = Master_ESport.verPeticionJugador();
            Master_ESport.borrarPeticion(d.get(r).getNickname());
            
            Master_ESport.list.remove(r);
            
            showMessageDialog(this, "Peticion denegada");
            
        }
        catch (Exception e) {
            
            showMessageDialog(this, e.getMessage());
        }

    }
    

            
            /**
             * This method is called from within the constructor to initialize the form.
             * WARNING: Do NOT modify this code. The content of this method is always
             * regenerated by the Form Editor.
             */
            @SuppressWarnings("unchecked")
            // <editor-fold defaultstate="collapsed" desc="Generated Code">
            
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDuenno = new javax.swing.JScrollPane();
        jpl = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jDuenno.setViewportView(jpl);

        jButton1.setForeground(new java.awt.Color(51, 255, 51));
        jButton1.setText("✔");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setForeground(new java.awt.Color(255, 0, 51));
        jButton2.setText("✖");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()

        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()

        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        if(jpl.getSelectedIndex()==-1){

            showMessageDialog(this, "Seleccione una peticion por favor");
        }
        else{
            if(jpl.getSelectedValue().substring(15, 21).equals("duenno")){

                aceptarPeticionDuenno(jpl.getSelectedIndex());
            }
            else if(jpl.getSelectedValue().substring(15, 21).equals("equipo")){

                aceptarPeticionEquipo(jpl.getSelectedIndex());
            }
            else if(jpl.getSelectedValue().substring(15, 22).equals("jugador")){

                aceptarPeticionJugador(jpl.getSelectedIndex());
            }
        }
 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        if(jpl.getSelectedIndex()==-1){

            showMessageDialog(this, "Seleccione una peticion por favor");
        }
        else{
            
            if(jpl.getSelectedValue().substring(15, 21).equals("duenno")){

                denegarPeticionDuenno(jpl.getSelectedIndex());
            }
            else if(jpl.getSelectedValue().substring(15, 21).equals("equipo")){

                denegarPeticionEquipo(jpl.getSelectedIndex());
            }
            else if(jpl.getSelectedValue().substring(15, 22).equals("jugador")){

                denegarPeticionJugador(jpl.getSelectedIndex());
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jDuenno;
    private javax.swing.JList<String> jpl;
    // End of variables declaration//GEN-END:variables
}
